"""End to end through the real API, with the AI and weather services replaced by fixed answers."""
from datetime import datetime, timedelta

import pytest
from fastapi.testclient import TestClient

from app.main import app
from app.services import pipeline, vision_service as vs
from tests.helpers import ai_generated_photo, ai_result, photo

NEXT_AI = {}


def fake_analyze(path, mime, project=None):
    raw = NEXT_AI.pop("raw", None) or ai_result()
    raw["visible_years"] = vs._years(raw.get("visible_text"))
    return {"status": "COMPLETED", "provider": "gemini", "error": None,
            "data": vs.EvidenceAnalysis(observations=raw["observations"], objects=raw["objects"],
                                        activities=raw["activities"], raw_response=raw)}


@pytest.fixture(scope="module")
def client():
    pipeline.vision_service.analyze_evidence = fake_analyze
    with TestClient(app) as c:
        yield c


def upload(c, data, name, **form):
    r = c.post("/api/evidence/upload", data={k: str(v) for k, v in form.items()},
               files={"file": (name, data, "image/jpeg")})
    assert r.status_code == 200, r.text
    return r.json()["evidence"]


def status(c, eid):
    return c.get(f"/api/evidence/{eid}").json()["integrity"]["status"]


def test_full_flow(client):
    c = client
    pid = c.get("/api/projects").json()[0]["id"]
    today = datetime.now()
    r = c.put(f"/api/projects/{pid}", json={"name": "Riverbank cleanup", "description": "Clearing litter",
                                            "organization": "Green Hands",
                                            "start_date": (today - timedelta(days=60)).date().isoformat(),
                                            "end_date": (today + timedelta(days=30)).date().isoformat()})
    assert r.status_code == 200
    site = c.post(f"/api/projects/{pid}/sites", json={"name": "North bank", "latitude": 26.9, "longitude": 75.8,
                                                      "radius_m": 500}).json()

    t0 = today - timedelta(days=20)
    before = upload(c, photo(1, 26.9001, 75.8001, t0), "before.jpg", project_id=pid)
    after = upload(c, photo(2, 26.9002, 75.8001, t0 + timedelta(hours=6)), "after.jpg", project_id=pid)
    assert status(c, before["id"]) == "CORROBORATED"
    assert status(c, after["id"]) == "CORROBORATED"
    assert c.get(f"/api/evidence/{before['id']}").json()["site_id"] == site["id"]

    # Reused: cropped, recompressed copy without metadata (e.g. saved from an old report)
    reused = upload(c, photo(1, crop=12), "reused.jpg", project_id=pid)
    d = c.get(f"/api/evidence/{reused['id']}").json()
    assert d["integrity"]["status"] == "SUSPICIOUS"
    assert d["integrity"]["signals"]["reuse"]["status"] == "fail"
    assert d["duplicate_matches"][0]["id"] == before["id"]
    assert status(c, before["id"]) == "CORROBORATED", "the original must not be flagged"

    # Same spot, 10 days later, nothing changed: could be a re-used photo, so a person decides
    NEXT_AI["raw"] = ai_result()
    same_view = upload(c, photo(1, 26.9001, 75.8001, t0 + timedelta(days=10)), "same_view.jpg", project_id=pid)
    d = c.get(f"/api/evidence/{same_view['id']}").json()
    assert d["integrity"]["signals"]["reuse"]["status"] == "warn", d["integrity"]["signals"]["reuse"]
    # Same spot, later, with a visible change: genuine before/after, not reuse
    NEXT_AI["raw"] = ai_result(waste_visible=False)
    cleaned = upload(c, photo(1, 26.9001, 75.8001, t0 + timedelta(days=11), crop=4), "cleaned.jpg", project_id=pid)
    d = c.get(f"/api/evidence/{cleaned['id']}").json()
    assert d["integrity"]["signals"]["reuse"]["status"] == "pass", d["integrity"]["signals"]["reuse"]
    assert "before-and-after" in d["integrity"]["signals"]["reuse"]["reason"]

    far = upload(c, photo(3, 27.2, 76.1, t0), "far.jpg", project_id=pid)
    assert status(c, far["id"]) == "SUSPICIOUS"

    stripped = upload(c, photo(4), "whatsapp.jpg", project_id=pid)
    d = c.get(f"/api/evidence/{stripped['id']}").json()
    assert d["integrity"]["status"] == "UNVERIFIABLE"
    assert all(s["status"] != "fail" for s in d["integrity"]["signals"].values())

    aigen = upload(c, ai_generated_photo(), "chatgpt.jpg", project_id=pid)
    d = c.get(f"/api/evidence/{aigen['id']}").json()
    assert d["integrity"]["status"] == "SUSPICIOUS"
    assert d["integrity"]["signals"]["provenance"]["status"] == "fail"
    assert "generated by AI" in d["integrity"]["signals"]["provenance"]["reason"]

    dup = upload(c, photo(2, 26.9002, 75.8001, t0 + timedelta(hours=6)), "after_again.jpg", project_id=pid)
    d = c.get(f"/api/evidence/{dup['id']}").json()
    assert d["integrity"]["signals"]["reuse"]["status"] == "warn"
    assert d["integrity"]["status"] == "NEEDS_REVIEW"

    NEXT_AI["raw"] = ai_result(visible_text=["GU-WATER.ORG", "HND/AUL/01/2013"], visible_organizations=["GU-WATER.ORG"])
    old_sign = upload(c, photo(5, 26.9003, 75.8002, t0 + timedelta(days=1)), "tank.jpg", project_id=pid)
    d = c.get(f"/api/evidence/{old_sign['id']}").json()
    assert d["integrity"]["signals"]["text"]["status"] == "warn"
    assert "2013" in d["integrity"]["signals"]["text"]["reason"]
    assert "GU-WATER.ORG" in d["integrity"]["signals"]["text"]["reason"]

    NEXT_AI["raw"] = ai_result(is_collage_or_composite=True, collage_reason="three panels")
    collage = upload(c, photo(6, 26.9004, 75.8002, t0 + timedelta(days=2)), "collage.jpg", project_id=pid)
    assert c.get(f"/api/evidence/{collage['id']}").json()["integrity"]["signals"]["content"]["status"] == "warn"

    edited = upload(c, photo(7, 26.9004, 75.8003, t0 + timedelta(days=2), software="Adobe Photoshop 25.1"),
                    "edited.jpg", project_id=pid)
    assert status(c, edited["id"]) == "NEEDS_REVIEW"

    # In-app capture: token + live GPS; the file itself has no metadata
    tok = c.get(f"/api/capture/token?project_id={pid}&site_id={site['id']}").json()["token"]
    live = upload(c, photo(8), "capture.jpg", project_id=pid, site_id=site["id"], capture_token=tok,
                  gps_lat=26.9005, gps_lng=75.8004, gps_accuracy=12, tz_offset_min=-330,
                  client_time=datetime.utcnow().isoformat())
    d = c.get(f"/api/evidence/{live['id']}").json()
    assert d["capture_source"] == "in_app"
    assert d["integrity"]["signals"]["capture"]["status"] == "pass"
    assert d["integrity"]["status"] == "CORROBORATED", d["integrity"]
    reuse_token = upload(c, photo(9), "capture2.jpg", project_id=pid, capture_token=tok, gps_lat=26.9005,
                         gps_lng=75.8004, gps_accuracy=12)
    assert c.get(f"/api/evidence/{reuse_token['id']}").json()["integrity"]["signals"]["capture"]["status"] == "warn"

    # Review queue and decisions, with audit trail
    queue = c.get(f"/api/review/queue?project_id={pid}").json()
    assert queue[0]["integrity_status"] == "SUSPICIOUS"
    bad = c.post(f"/api/evidence/{edited['id']}/review", json={"decision": "APPROVED", "reason": "ok", "reviewer": "A"})
    assert bad.status_code == 422
    r = c.post(f"/api/evidence/{edited['id']}/review",
               json={"decision": "APPROVED", "reason": "Only brightness was adjusted; confirmed with volunteer.",
                     "reviewer": "Disha"})
    assert r.json()["integrity"]["status"] == "CORROBORATED"
    assert r.json()["integrity"]["engine_status"] == "NEEDS_REVIEW"
    c.post(f"/api/evidence/{aigen['id']}/review",
           json={"decision": "REJECTED", "reason": "AI-generated image, not field evidence.", "reviewer": "Disha"})
    assert status(c, aigen["id"]) == "REJECTED"
    hist = c.get(f"/api/evidence/{edited['id']}/history").json()
    assert [h["action"] for h in hist][0] == "received"
    assert any(h["action"] == "review" for h in hist)

    # Claims
    claim = c.post("/api/claims/", json={"text": "Volunteers cleared litter from the north bank.", "project_id": pid}).json()
    for eid in (before["id"], after["id"]):
        c.post(f"/api/claims/{claim['id']}/evidence", json={"evidence_id": eid})
    assert c.get(f"/api/claims/{claim['id']}").json()["support"]["state"] == "SUPPORTED"
    c.post(f"/api/claims/{claim['id']}/evidence", json={"evidence_id": reused["id"]})
    detail = c.get(f"/api/claims/{claim['id']}").json()
    assert detail["support"]["state"] == "CONTESTED"
    rep = c.get(f"/api/claims/{claim['id']}/report").json()
    assert {x["id"] for x in rep["supporting"]} == {before["id"], after["id"]}
    assert rep["flagged"][0]["id"] == reused["id"] and rep["flagged"][0]["reasons"]
    assert len(rep["pairs"]) == 1
    pub = c.get(f"/api/public/claims/{detail['public_token']}").json()
    assert pub["claim_text"] == claim["text"] and "evidence" not in pub
    assert c.get("/api/public/claims/nope").status_code == 404
    qr = c.get(f"/api/claims/{claim['id']}/qr.svg")
    assert qr.status_code == 200 and qr.text.startswith("<svg")

    pairs = c.get(f"/api/projects/{pid}/pairs").json()
    assert any(p["before"] == before["id"] for p in pairs)

    ov = c.get(f"/api/projects/{pid}/overview").json()
    assert ov["counts"]["SUSPICIOUS"] >= 2 and ov["sites"][0]["corroborated_count"] >= 2
    assert c.get(f"/api/sites/{site['id']}/reference").json()["reference"] is not None
    res = c.post("/api/evidence/search", json={"query": "litter", "project_id": pid}).json()
    assert res["mode"] == "keyword" and res["results"]


def test_weather_mismatch(client, monkeypatch):
    from app.services import weather_service
    monkeypatch.setattr(pipeline.weather_service, "lookup", lambda *a: {"precip_24h_mm": 0.0, "precip_3h_mm": 0.0,
                                                                        "precip_at_hour_mm": 0.0, "source": "test"})
    pid = client.get("/api/projects").json()[0]["id"]
    NEXT_AI["raw"] = ai_result(ground_wet=True)
    e = upload(client, photo(20, 26.9006, 75.8005, datetime.now() - timedelta(days=3)), "wet.jpg", project_id=pid)
    sig = client.get(f"/api/evidence/{e['id']}").json()["integrity"]["signals"]["weather"]
    assert sig["status"] == "warn" and "wet ground" in sig["reason"]
    assert weather_service is not None


def test_rejects_non_images(client):
    r = client.post("/api/evidence/upload", files={"file": ("x.jpg", b"not an image", "image/jpeg")})
    assert r.status_code == 400
