"""Content credentials (C2PA) and IPTC digital-source-type checks.

Images from ChatGPT, Adobe Firefly, Microsoft Designer and others embed C2PA content
credentials that say the image was generated by AI. Screenshots and re-saves strip them,
so "no credentials" never counts against a photo.
"""
import json
import re

AI_SOURCE_TYPES = ("trainedalgorithmicmedia", "algorithmicmedia", "compositesynthetic")
AI_EDIT_SOURCE_TYPES = ("compositewithtrainedalgorithmicmedia", "algorithmicallyenhanced")
CAPTURE_SOURCE_TYPES = ("digitalcapture", "computationalcapture", "compositecapture")
KNOWN_GENERATORS = ("openai", "chatgpt", "dall", "gpt-4o", "gpt-image", "sora", "firefly", "midjourney",
                    "stable diffusion", "imagen", "gemini", "bing image", "designer", "copilot", "leonardo",
                    "ideogram", "flux", "grok", "aurora", "meta ai")


def _source_kind(value: str) -> str | None:
    v = (value or "").lower().rsplit("/", 1)[-1]
    if any(v == t or v.endswith(t) for t in AI_EDIT_SOURCE_TYPES):
        return "ai_edited"
    if any(v == t for t in AI_SOURCE_TYPES):
        return "ai_generated"
    if any(v == t for t in CAPTURE_SOURCE_TYPES):
        return "camera"
    return None


def _walk_actions(manifest: dict):
    for a in manifest.get("assertions", []) or []:
        if str(a.get("label", "")).startswith("c2pa.actions"):
            for act in (a.get("data") or {}).get("actions", []) or []:
                yield act


def _tool_names(manifest: dict) -> list[str]:
    names = []
    for g in manifest.get("claim_generator_info", []) or []:
        if g.get("name"):
            names.append(str(g["name"]))
    if manifest.get("claim_generator"):
        names.append(str(manifest["claim_generator"]).split("/")[0].replace("_", " "))
    for act in _walk_actions(manifest):
        agent = act.get("softwareAgent")
        if isinstance(agent, dict) and agent.get("name"):
            names.append(str(agent["name"]))
        elif isinstance(agent, str):
            names.append(agent)
    sig = manifest.get("signature_info") or {}
    if sig.get("issuer"):
        names.append(str(sig["issuer"]))
    seen, out = set(), []
    for n in names:
        if n.lower() not in seen:
            seen.add(n.lower())
            out.append(n)
    return out


def read_c2pa(path: str) -> dict | None:
    try:
        import c2pa
    except Exception:
        return None
    try:
        reader = c2pa.Reader(path)
    except Exception:
        return None   # no manifest, or unsupported format
    try:
        data = json.loads(reader.json())
        state = None
        try:
            state = reader.get_validation_state()
        except Exception:
            pass
    finally:
        try:
            reader.close()
        except Exception:
            pass
    active = (data.get("manifests") or {}).get(data.get("active_manifest") or "", {})
    codes = [v.get("code", "") for v in data.get("validation_status", []) or []]
    kinds = []
    for m in (data.get("manifests") or {}).values():
        for act in _walk_actions(m):
            k = _source_kind(act.get("digitalSourceType", ""))
            if k:
                kinds.append(k)
    tools = _tool_names(active)
    sig = active.get("signature_info") or {}
    return {
        "found": True,
        "validation_state": str(state) if state is not None else None,
        "validation_codes": codes,
        "tampered": any(c.startswith(("assertion.dataHash.mismatch", "claimSignature.mismatch", "assertion.hashedURI.mismatch"))
                        for c in codes) or str(state).lower() == "invalid",
        "source_kinds": kinds,
        "tools": tools,
        "signer": sig.get("issuer") or sig.get("common_name"),
        "signed_at": sig.get("time"),
        "title": active.get("title"),
    }


def scan_bytes(data: bytes) -> dict:
    """Fallback: look for IPTC/XMP digital-source-type markers written by AI tools."""
    text = data[:600_000].decode("latin-1", "ignore") + data[-200_000:].decode("latin-1", "ignore")
    low = text.lower()
    kinds = []
    for m in re.finditer(r"digitalsourcetype[^a-z]{0,80}?([a-z]+)(?:[\"'<\s])", low):
        k = _source_kind(m.group(1))
        if k:
            kinds.append(k)
    if "trainedalgorithmicmedia" in low and not kinds:
        kinds.append("ai_generated")
    tools = [g for g in KNOWN_GENERATORS if g in low and ("c2pa" in low or "digitalsourcetype" in low)]
    return {"source_kinds": kinds, "tools": tools, "has_c2pa_marker": "c2pa" in low and "jumb" in low}


def assess(path: str, data: bytes) -> dict:
    """Returns a summary the trust engine can use directly."""
    manifest = read_c2pa(path)
    scan = scan_bytes(data)
    kinds = list((manifest or {}).get("source_kinds", [])) + scan["source_kinds"]
    tools = list((manifest or {}).get("tools", [])) + [t for t in scan["tools"]]
    if "ai_generated" in kinds:
        verdict = "ai_generated"
    elif "ai_edited" in kinds:
        verdict = "ai_edited"
    elif manifest and manifest.get("tampered"):
        verdict = "tampered"
    elif "camera" in kinds:
        verdict = "camera"
    elif manifest:
        verdict = "credentials_present"
    elif scan["has_c2pa_marker"]:
        verdict = "credentials_unreadable"
    else:
        verdict = "none"
    seen, uniq_tools = set(), []
    for t in tools:
        if t.lower() not in seen:
            seen.add(t.lower())
            uniq_tools.append(t)
    return {"verdict": verdict, "tools": uniq_tools[:5], "manifest": manifest, "iptc_source_kinds": scan["source_kinds"]}
